conditions = ["sun",
              "cloud",
              "rain",
              "heavy rain",
              "shower",
              "storm",
              "thunder",
              "lightning",
              "hail",
              "snow",
              "cyclone",
              "wind"
              "partly cloudy",
              "light showers",
              "tornado"]

translation = {"sun": "sun",
               "cloud": "cloud_250",
               "rain": "rain",
               "heavy rain": "heavy_rain",
               "shower": "rain",
               "storm": "storm",
               "thunder": "storm",
               "lightning": "storm",
               "hail": "hail",
               "snow": "snow",
               "cyclone": "cyclone",
               "wind": "wind",
               "partly cloudy": "cloud",
               "light showers": "rain",
               "tornado": "cyclone"}